version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_KEY
      - CURRENCY_API_URL
      - STORMGLASS_API_URL
      - STORMGLASS_API_KEY
      - METEOSOURCE_API_URL1
      - METEOSOURCE_API_URL2